= POSRČ project
:sectnums:

== Run FreeRTOS & blink LEDs
:fb: footnote:[Mastering the FreeRTOS Real Time Kernel, by Richard Barry and the FreeRTOS Team. Release version 1.1.0. Available from https://freertos.org/Documentation/02-Kernel/07-Books-and-manual/01-RTOS_book]

Just run it -- but still, I need some reference, I don't remember the API anymore. I guess that, as it is usually is, going to the source is always best -- so I'm using _the book_ {fb}.

At this time, I'll just go with the as-quick-as-possible approach, so I won't go through those chapters. But I will later.

* First it would be nice to have some IO. The big LED will do for now
** Is there any board support package, that would abstract me away from registers?
*** Yes, but I'm quite confused from it. But let's use the `fsl_gpio.c` driver. However, that calls for a simplified schematic diagram. Let's fire up KiCAD.
** Draw a schematic diagram

== TODO

* Add board's schematic diagram ✅
* Run some UART print
* List MCU's params in this file
* Depict the project's structure (tasks, queues, ...) using PlantUML
* Find out how to use FreeRTOS-aware debugging here in Eclipse
* Will links to source files work here, in text and in PlantUML diagrams like in IntelliJ?
* What are the ConfigTools in MCUXpresso?
* Some Git GUI for MCUXpresso? And GitLab GUI?

.PlantUML works here in Eclipse too!
[plantuml, align=center]
----
@startuml
PC -> MCU : UART: ""hello\\n""
@enduml
----

== What would be interesting to try

=== ITM

What exactly does it offer? How is it used? There is the interesting `Analysis` tab in MCUXpresso...

=== Embedded scripting engine
:ll: https://www.lua.org/
:el: https://eluaproject.net/
:wr: https://wren.io/
:tu: https://docs.tinyusb.org/en/latest/index.html
:lu: https://libusb.info/

I'd just like to try some out. But the choice isn't trivial, here on M0+.

=== USB

Send data over it (likely using {tu}[TinyUSB]), and catch it on the PC side, likely using {lu}[libusb]. 